//vetor = [12,22];
//console.log(vetor.length);
//a = 10;
//b = 22;
//c = 15;
//v = [10,22,15];
vetor = [];
vetor[0] = "Thiago";
vetor[1] = "Aloíso";
vetor[2] = "Bruno";
w = vetor;
w[1] = "Mariana";
vetor[5] = "Igor";
console.log(vetor);
